create type "public"."game-state" as enum ('playing', 'paused');

create type "public"."task_type" as enum ('attack', 'attack_and_claim', 'repair', 'claim');

create schema if not exists "game";

create type "game"."game-state" as enum ('playing');

create type "game"."test" as enum ('test');

create table "game"."fraction" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
);


alter table "game"."fraction" enable row level security;

create table "game"."game" (
    "tick" bigint not null,
    "state" "game-state" not null default 'paused'::"game-state"
);


alter table "game"."game" enable row level security;

create table "game"."point" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "max_health" smallint not null default '255'::smallint,
    "name" text not null
);


alter table "game"."point" enable row level security;

create table "game"."tick_point" (
    "created_at" timestamp with time zone not null default now(),
    "point_id" uuid not null,
    "tick" bigint not null,
    "health" smallint not null,
    "acquired_by" bigint not null
);


alter table "game"."tick_point" enable row level security;

create table "game"."tick_task" (
    "created_at" timestamp with time zone not null default now(),
    "created_by" uuid not null default gen_random_uuid(),
    "tick" bigint not null,
    "point" uuid not null,
    "type" task_type not null
);


alter table "game"."tick_task" enable row level security;

create table "game"."user" (
    "id" uuid not null,
    "fraction" bigint not null
);


alter table "game"."user" enable row level security;

CREATE UNIQUE INDEX fraction_name_key ON game.fraction USING btree (name);

CREATE UNIQUE INDEX fraction_pkey ON game.fraction USING btree (id);

CREATE UNIQUE INDEX point_name_key ON game.point USING btree (name);

CREATE UNIQUE INDEX point_pkey ON game.point USING btree (id);

CREATE UNIQUE INDEX tick_point_pkey ON game.tick_point USING btree (point_id, tick);

CREATE UNIQUE INDEX tick_task_pkey ON game.tick_task USING btree (created_by, tick);

CREATE UNIQUE INDEX user_pkey ON game."user" USING btree (id);

alter table "game"."fraction" add constraint "fraction_pkey" PRIMARY KEY using index "fraction_pkey";

alter table "game"."point" add constraint "point_pkey" PRIMARY KEY using index "point_pkey";

alter table "game"."tick_point" add constraint "tick_point_pkey" PRIMARY KEY using index "tick_point_pkey";

alter table "game"."tick_task" add constraint "tick_task_pkey" PRIMARY KEY using index "tick_task_pkey";

alter table "game"."user" add constraint "user_pkey" PRIMARY KEY using index "user_pkey";

alter table "game"."fraction" add constraint "fraction_name_key" UNIQUE using index "fraction_name_key";

alter table "game"."point" add constraint "point_name_key" UNIQUE using index "point_name_key";

alter table "game"."tick_point" add constraint "tick_point_acquired_by_fkey" FOREIGN KEY (acquired_by) REFERENCES game.fraction(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "game"."tick_point" validate constraint "tick_point_acquired_by_fkey";

alter table "game"."tick_point" add constraint "tick_point_point_id_fkey" FOREIGN KEY (point_id) REFERENCES game.point(id) not valid;

alter table "game"."tick_point" validate constraint "tick_point_point_id_fkey";

alter table "game"."tick_task" add constraint "tick_task_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "game"."tick_task" validate constraint "tick_task_created_by_fkey";

alter table "game"."tick_task" add constraint "tick_task_point_fkey" FOREIGN KEY (point) REFERENCES game.point(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "game"."tick_task" validate constraint "tick_task_point_fkey";

alter table "game"."user" add constraint "user_fraction_fkey" FOREIGN KEY (fraction) REFERENCES game.fraction(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "game"."user" validate constraint "user_fraction_fkey";

alter table "game"."user" add constraint "user_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "game"."user" validate constraint "user_id_fkey";
