alter table "public"."game" add column "id" smallint generated by default as identity not null;

CREATE UNIQUE INDEX game_id_key ON public.game USING btree (id);

CREATE UNIQUE INDEX game_pkey ON public.game USING btree (id);

alter table "public"."game" add constraint "game_pkey" PRIMARY KEY using index "game_pkey";

alter table "public"."game" add constraint "game_id_key" UNIQUE using index "game_id_key";


