create type "public"."game-state" as enum ('playing', 'paused');

create type "public"."task_type" as enum ('attack', 'attack_and_claim', 'repair', 'claim');

create table "public"."fraction" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
);


alter table "public"."fraction" enable row level security;

create table "public"."game" (
    "tick" bigint not null,
    "state" "game-state" not null default 'paused'::"game-state",
    "id" smallint generated by default as identity not null
);


alter table "public"."game" enable row level security;

create table "public"."point" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "max_health" smallint not null default '255'::smallint,
    "name" text not null
);


alter table "public"."point" enable row level security;

create table "public"."tick_point" (
    "created_at" timestamp with time zone not null default now(),
    "point_id" uuid not null,
    "tick" bigint not null,
    "health" smallint not null,
    "acquired_by" uuid
);


alter table "public"."tick_point" enable row level security;

create table "public"."tick_task" (
    "created_at" timestamp with time zone not null default now(),
    "created_by" uuid not null,
    "tick" bigint not null,
    "point" uuid not null,
    "type" task_type not null,
    "id" uuid not null default gen_random_uuid()
);


alter table "public"."tick_task" enable row level security;

create table "public"."user" (
    "id" uuid not null,
    "fraction" uuid not null,
    "name" text not null default ''::text
);


alter table "public"."user" enable row level security;

CREATE UNIQUE INDEX fraction_name_key ON public.fraction USING btree (name);

CREATE UNIQUE INDEX fraction_pkey ON public.fraction USING btree (id);

CREATE UNIQUE INDEX game_id_key ON public.game USING btree (id);

CREATE UNIQUE INDEX game_pkey ON public.game USING btree (id);

CREATE UNIQUE INDEX point_name_key ON public.point USING btree (name);

CREATE UNIQUE INDEX point_pkey ON public.point USING btree (id);

CREATE UNIQUE INDEX tick_point_pkey ON public.tick_point USING btree (point_id, tick);

CREATE UNIQUE INDEX tick_task_pkey ON public.tick_task USING btree (id);

CREATE UNIQUE INDEX user_name_key ON public."user" USING btree (name);

CREATE UNIQUE INDEX user_pkey ON public."user" USING btree (id);

alter table "public"."fraction" add constraint "fraction_pkey" PRIMARY KEY using index "fraction_pkey";

alter table "public"."game" add constraint "game_pkey" PRIMARY KEY using index "game_pkey";

alter table "public"."point" add constraint "point_pkey" PRIMARY KEY using index "point_pkey";

alter table "public"."tick_point" add constraint "tick_point_pkey" PRIMARY KEY using index "tick_point_pkey";

alter table "public"."tick_task" add constraint "tick_task_pkey" PRIMARY KEY using index "tick_task_pkey";

alter table "public"."user" add constraint "user_pkey" PRIMARY KEY using index "user_pkey";

alter table "public"."fraction" add constraint "fraction_name_key" UNIQUE using index "fraction_name_key";

alter table "public"."game" add constraint "game_id_key" UNIQUE using index "game_id_key";

alter table "public"."point" add constraint "point_name_key" UNIQUE using index "point_name_key";

alter table "public"."tick_point" add constraint "tick_point_acquired_by_fkey" FOREIGN KEY (acquired_by) REFERENCES fraction(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."tick_point" validate constraint "tick_point_acquired_by_fkey";

alter table "public"."tick_point" add constraint "tick_point_point_id_fkey" FOREIGN KEY (point_id) REFERENCES point(id) not valid;

alter table "public"."tick_point" validate constraint "tick_point_point_id_fkey";

alter table "public"."tick_task" add constraint "tick_task_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."tick_task" validate constraint "tick_task_created_by_fkey";

alter table "public"."tick_task" add constraint "tick_task_point_fkey" FOREIGN KEY (point) REFERENCES point(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."tick_task" validate constraint "tick_task_point_fkey";

alter table "public"."user" add constraint "user_fraction_fkey" FOREIGN KEY (fraction) REFERENCES fraction(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."user" validate constraint "user_fraction_fkey";

alter table "public"."user" add constraint "user_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user" validate constraint "user_id_fkey";

alter table "public"."user" add constraint "user_name_check" CHECK ((length(name) < 50)) not valid;

alter table "public"."user" validate constraint "user_name_check";

alter table "public"."user" add constraint "user_name_key" UNIQUE using index "user_name_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.check_if_user_already_added_a_task_for_current_tick(a_user_id uuid)
 RETURNS boolean
 LANGUAGE sql
AS $function$
SELECT EXISTS (
  SELECT 1 FROM public.tick_task WHERE created_by=a_user_id AND tick=(SELECT tick from public.game)
);
$function$
;

CREATE OR REPLACE FUNCTION public.does_point_exists(a_point_id uuid)
 RETURNS boolean
 LANGUAGE sql
AS $function$
SELECT EXISTS (
  SELECT 1 FROM public.point WHERE id = a_point_id
) AS exists_bool;
$function$
;

CREATE OR REPLACE FUNCTION public.get_all_points_for_current_tick()
 RETURNS jsonb
 LANGUAGE sql
  AS $function$SELECT point.id, point.max_health, tick_point.health, tick_point.acquired_by 
  FROM tick_point
  LEFT JOIN point
  ON point.id=tick_point.point_id
  WHERE tick_point.tick = (select get_current_tick());$function$
;

CREATE OR REPLACE FUNCTION public.get_all_users_for_current_tick()
 RETURNS jsonb
 LANGUAGE sql
AS $function$SELECT * 
FROM public.user 
WHERE id IN (
  SELECT DISTINCT created_by 
  FROM public.tick_task 
  WHERE tick = (
    select get_current_tick()
  )
);$function$
;

CREATE OR REPLACE FUNCTION public.get_current_tick()
 RETURNS bigint
 LANGUAGE sql
AS $function$SELECT tick from public.game$function$
;

CREATE OR REPLACE FUNCTION public.select_point_states_of_current_tick()
 RETURNS jsonb
 LANGUAGE sql
AS $function$
SELECT * FROM public.tick_point WHERE tick=(SELECT tick from public.game)
$function$
;

CREATE OR REPLACE FUNCTION public.select_point_states_of_tick(a_tick bigint)
 RETURNS jsonb
 LANGUAGE sql
AS $function$
SELECT * FROM public.tick_point WHERE tick=a_tick
$function$
;

CREATE OR REPLACE FUNCTION public.select_task_of_current_tick()
 RETURNS jsonb
 LANGUAGE sql
AS $function$
SELECT * FROM public.tick_task WHERE tick=(SELECT tick from public.game)
$function$
;

grant delete on table "public"."fraction" to "anon";

grant insert on table "public"."fraction" to "anon";

grant references on table "public"."fraction" to "anon";

grant select on table "public"."fraction" to "anon";

grant trigger on table "public"."fraction" to "anon";

grant truncate on table "public"."fraction" to "anon";

grant update on table "public"."fraction" to "anon";

grant delete on table "public"."fraction" to "authenticated";

grant insert on table "public"."fraction" to "authenticated";

grant references on table "public"."fraction" to "authenticated";

grant select on table "public"."fraction" to "authenticated";

grant trigger on table "public"."fraction" to "authenticated";

grant truncate on table "public"."fraction" to "authenticated";

grant update on table "public"."fraction" to "authenticated";

grant delete on table "public"."fraction" to "service_role";

grant insert on table "public"."fraction" to "service_role";

grant references on table "public"."fraction" to "service_role";

grant select on table "public"."fraction" to "service_role";

grant trigger on table "public"."fraction" to "service_role";

grant truncate on table "public"."fraction" to "service_role";

grant update on table "public"."fraction" to "service_role";

grant delete on table "public"."game" to "anon";

grant insert on table "public"."game" to "anon";

grant references on table "public"."game" to "anon";

grant select on table "public"."game" to "anon";

grant trigger on table "public"."game" to "anon";

grant truncate on table "public"."game" to "anon";

grant update on table "public"."game" to "anon";

grant delete on table "public"."game" to "authenticated";

grant insert on table "public"."game" to "authenticated";

grant references on table "public"."game" to "authenticated";

grant select on table "public"."game" to "authenticated";

grant trigger on table "public"."game" to "authenticated";

grant truncate on table "public"."game" to "authenticated";

grant update on table "public"."game" to "authenticated";

grant delete on table "public"."game" to "service_role";

grant insert on table "public"."game" to "service_role";

grant references on table "public"."game" to "service_role";

grant select on table "public"."game" to "service_role";

grant trigger on table "public"."game" to "service_role";

grant truncate on table "public"."game" to "service_role";

grant update on table "public"."game" to "service_role";

grant delete on table "public"."point" to "anon";

grant insert on table "public"."point" to "anon";

grant references on table "public"."point" to "anon";

grant select on table "public"."point" to "anon";

grant trigger on table "public"."point" to "anon";

grant truncate on table "public"."point" to "anon";

grant update on table "public"."point" to "anon";

grant delete on table "public"."point" to "authenticated";

grant insert on table "public"."point" to "authenticated";

grant references on table "public"."point" to "authenticated";

grant select on table "public"."point" to "authenticated";

grant trigger on table "public"."point" to "authenticated";

grant truncate on table "public"."point" to "authenticated";

grant update on table "public"."point" to "authenticated";

grant delete on table "public"."point" to "service_role";

grant insert on table "public"."point" to "service_role";

grant references on table "public"."point" to "service_role";

grant select on table "public"."point" to "service_role";

grant trigger on table "public"."point" to "service_role";

grant truncate on table "public"."point" to "service_role";

grant update on table "public"."point" to "service_role";

grant delete on table "public"."tick_point" to "anon";

grant insert on table "public"."tick_point" to "anon";

grant references on table "public"."tick_point" to "anon";

grant select on table "public"."tick_point" to "anon";

grant trigger on table "public"."tick_point" to "anon";

grant truncate on table "public"."tick_point" to "anon";

grant update on table "public"."tick_point" to "anon";

grant delete on table "public"."tick_point" to "authenticated";

grant insert on table "public"."tick_point" to "authenticated";

grant references on table "public"."tick_point" to "authenticated";

grant select on table "public"."tick_point" to "authenticated";

grant trigger on table "public"."tick_point" to "authenticated";

grant truncate on table "public"."tick_point" to "authenticated";

grant update on table "public"."tick_point" to "authenticated";

grant delete on table "public"."tick_point" to "service_role";

grant insert on table "public"."tick_point" to "service_role";

grant references on table "public"."tick_point" to "service_role";

grant select on table "public"."tick_point" to "service_role";

grant trigger on table "public"."tick_point" to "service_role";

grant truncate on table "public"."tick_point" to "service_role";

grant update on table "public"."tick_point" to "service_role";

grant delete on table "public"."tick_task" to "anon";

grant insert on table "public"."tick_task" to "anon";

grant references on table "public"."tick_task" to "anon";

grant select on table "public"."tick_task" to "anon";

grant trigger on table "public"."tick_task" to "anon";

grant truncate on table "public"."tick_task" to "anon";

grant update on table "public"."tick_task" to "anon";

grant delete on table "public"."tick_task" to "authenticated";

grant insert on table "public"."tick_task" to "authenticated";

grant references on table "public"."tick_task" to "authenticated";

grant select on table "public"."tick_task" to "authenticated";

grant trigger on table "public"."tick_task" to "authenticated";

grant truncate on table "public"."tick_task" to "authenticated";

grant update on table "public"."tick_task" to "authenticated";

grant delete on table "public"."tick_task" to "service_role";

grant insert on table "public"."tick_task" to "service_role";

grant references on table "public"."tick_task" to "service_role";

grant select on table "public"."tick_task" to "service_role";

grant trigger on table "public"."tick_task" to "service_role";

grant truncate on table "public"."tick_task" to "service_role";

grant update on table "public"."tick_task" to "service_role";

grant delete on table "public"."user" to "anon";

grant insert on table "public"."user" to "anon";

grant references on table "public"."user" to "anon";

grant select on table "public"."user" to "anon";

grant trigger on table "public"."user" to "anon";

grant truncate on table "public"."user" to "anon";

grant update on table "public"."user" to "anon";

grant delete on table "public"."user" to "authenticated";

grant insert on table "public"."user" to "authenticated";

grant references on table "public"."user" to "authenticated";

grant select on table "public"."user" to "authenticated";

grant trigger on table "public"."user" to "authenticated";

grant truncate on table "public"."user" to "authenticated";

grant update on table "public"."user" to "authenticated";

grant delete on table "public"."user" to "service_role";

grant insert on table "public"."user" to "service_role";

grant references on table "public"."user" to "service_role";

grant select on table "public"."user" to "service_role";

grant trigger on table "public"."user" to "service_role";

grant truncate on table "public"."user" to "service_role";

grant update on table "public"."user" to "service_role";

create policy "Enable read access for all users"
on "public"."fraction"
as permissive
for select
to authenticated, service_role
using (true);


create policy "Enable read access for authenticated users"
on "public"."game"
as permissive
for select
to authenticated, service_role
using (true);


create policy "Enable read access for authenticated users"
on "public"."point"
as permissive
for select
to authenticated, service_role
using (true);


create policy "Enable read access for authenticated users"
on "public"."tick_point"
as permissive
for select
to authenticated, service_role
using (true);


create policy "Enable delete for users based on user_id"
on "public"."tick_task"
as permissive
for delete
to public
using ((( SELECT auth.uid() AS uid) = created_by));


create policy "Enable insert for users based on user_id"
on "public"."tick_task"
as permissive
for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) = created_by));


create policy "Enable read access for all users"
on "public"."tick_task"
as permissive
for select
to authenticated, service_role
using (true);


create policy "Enable update for users based on user_id"
on "public"."tick_task"
as permissive
for update
to public
using ((( SELECT auth.uid() AS uid) = created_by));


create policy "Enable insert for users based on user_id"
on "public"."user"
as permissive
for insert
to authenticated, postgres
with check ((( SELECT auth.uid() AS uid) = id));


create policy "Enable users to view their own data only"
on "public"."user"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = id));



